# 1. Simulator parameters
use_sim_time: true
clockscale: 1.0                         # only 1.0 is supported yet

# 2. Vehicle initial geodetic position

# Zurich
lat_ref : 47.3985954655945
lon_ref : 8.546044093305426
alt_ref : 10

# Key point 1. Yard
# lat_ref : 55.7487847875
# lon_ref : 48.7430507069
# alt_ref : 5.9

# Key point 2. Delivery point (Magnet)
# lat_ref : 55.7503962494
# lon_ref : 48.7480952714
# alt_ref : 7.85

# Key point 3. Technopark office parking
# lat_ref : 55.7517506178
# lon_ref : 48.7506804476
# alt_ref : +8.5

# Key point 4. Buildings
# lat_ref : 55.7531869667
# lon_ref : 48.7510098844
# alt_ref : +5.5

# 3. Vehicle initial local position
# X, Y, Z, roll, pitch, yaw, weight
# N - [0,0,0,1], E - [0,0,0.7,0.7], S - [0,0,1,0], W - [0,0,0.7,-0.7]
init_pose: [0.00, 0.00, 0.0,
            0.00, 0.00, +0.00, +1.00]

# 4. Additional sensors set
esc_status: true
ice_status: true
fuel_tank_status: true
battery_status: true

# Environment parameters
wind_ned: [5.0, 0.0, 0.0]
wind_variance: 0.0
gust_ned: [0.0, 0.0, 0.0]
gust_variance: 0.0

# This is the standard acceleration due to gravity on Earth's surface.
# If you are simulating in a different planetary context or need slight
# variations due to altitude changes, you might adjust it slightly.
gravity: 9.80665  # m/s^2

# This is the standard atmospheric density at sea level at 15°C under
# International Standard Atmosphere (ISA) conditions. Atmospheric density
# decreases with altitude, so if you are simulating high-altitude UAV
# operations, you might use a lower value. For example:
# At 5000 m altitude: ~0.736 kg/m^3
# At 10,000 m altitude: ~0.413 kg/m^3
atmoRho: 1.2  # air density (kg/m^3)
