uavcan_node_id:           46
uavcan_node_name:         "hitl.sensors"
bridges:                  ["DiffPressureRosToUavcan",           "/uav/raw_air_data",

                           "EscStatusRosToUavcan",              "/uav/esc_status",
                           "IceReciprocatingStatusRosToUavcan", "/uav/ice",
                           "IceFuelTankStatusRosToUavcan",      "/uav/fuel_tank"
]
