uavcan_node_id:           41
uavcan_node_name:         "hitl.actuators"
bridges:                  ["RawCommandUavcanToRos",             "/uav/actuators_raw",
                           "ArrayCommandUavcanToRos",           "/uav/servo",
                           "ArmUavcanToRos",                    "/uav/arm"
]
