name: catkin_build

on: [push]

defaults:
  run:
    shell: bash
jobs:
  catkin_build:
    runs-on: ubuntu-20.04
    timeout-minutes: 8
    container:
      image: ros:noetic
    steps:
      - run: apt-get update && apt-get install -y git
      - run: if [[ "$ROS_DISTRO" = "noetic" ]] ;  then apt-get install -y python3-pip ros-noetic-catkin python3-catkin-tools ; fi

      - uses: actions/checkout@v2
        with:
          path: catkin_ws/src/uav_hitl_dynamics

      - name: Install requirements
        run: ./catkin_ws/src/uav_hitl_dynamics/install_requirements.sh

      - name: Dependencies
        run: |
          git clone https://github.com/RaccoonlabDev/geographiclib_conversions.git catkin_ws/src/geographiclib_conversions
          ./catkin_ws/src/geographiclib_conversions/scripts/install.sh

      - name: Catkin build
        run: source /opt/ros/noetic/setup.bash && cd catkin_ws && catkin build
